apiVersion: v1
kind: Service
metadata:
  name: order-load-balancer
  namespace: default
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30167 # - a static port assigned on each the node
      port: 8080 # - port exposed internally in the cluster
      targetPort: 8080 # - the container port to send requests to
  selector:
    app.kubernetes.io/name: order-service